### ISSUE TITLE
add new metadata region

### ISSUE THREAD

**Issue by SparkliTwizzl** [SparkliTwizzl/petrichor#125]
- [x] add required region `metadata` (blocked by #124)
- [x] add new region parser class to handle new region (blocked by #133)
- [x] add required token `minimum-version`
- [x] reject input files with `minimum-version` < current (blocked by #126 unless it's gonna be done through a janky stupid method)
- [x] update tests
- [x] update documentation
